[package]
name = "bobcat-entrypoints"
version = "0.1.5"
edition = "2024"
license = "MIT"
description = "Entrypoint helper types for Stylus entrypoint code."
homepage = "https://fluiditylabs.io"
repository = "https://github.com/fluidity-money/bobcat-entrypoints"

[dependencies]
bobcat-cd = { version = ">=0.11.7", features = ["derive"] }

[features]
alloc = ["bobcat-cd/alloc"]
